/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/regenerate-products-v2.js
 */
import { Product } from '@/types/product';

import Img_1_Main from '@/images/curated/bestsellers/amiparis-hoodie-001/front.webp';
const Img_1_Hover = Img_1_Main;
import Img_2_Main from '@/images/curated/bestsellers/amiparis-hoodie-002/front.webp';
const Img_2_Hover = Img_2_Main;
import Img_3_Main from '@/images/curated/bestsellers/amiparis-hoodie-003/front.webp';
import Img_3_Hover from '@/images/curated/bestsellers/amiparis-hoodie-003/back.webp';
import Img_3_Gal_1 from '@/images/curated/bestsellers/amiparis-hoodie-003/back.webp';
import Img_4_Main from '@/images/curated/bestsellers/amiparis-hoodie-004/front.webp';
import Img_4_Hover from '@/images/curated/bestsellers/amiparis-hoodie-004/back.webp';
import Img_4_Gal_1 from '@/images/curated/bestsellers/amiparis-hoodie-004/back.webp';
import Img_5_Main from '@/images/curated/bestsellers/amiparis-hoodie-005/front.webp';
const Img_5_Hover = Img_5_Main;
import Img_6_Main from '@/images/curated/bestsellers/amiparis-hoodie-006/front.webp';
const Img_6_Hover = Img_6_Main;
import Img_7_Main from '@/images/curated/bestsellers/amiparis-hoodie-007/front.webp';
const Img_7_Hover = Img_7_Main;
import Img_8_Main from '@/images/curated/bestsellers/amiparis-hoodie-008/front.webp';
const Img_8_Hover = Img_8_Main;
import Img_9_Main from '@/images/curated/sports/football/jordan/hoodies/jordan-hoodies-001/front.webp';
import Img_9_Hover from '@/images/curated/sports/football/jordan/hoodies/jordan-hoodies-001/back.webp';
import Img_9_Gal_1 from '@/images/curated/sports/football/jordan/hoodies/jordan-hoodies-001/back.webp';
import Img_10_Main from '@/images/curated/sports/football/jordan/hoodies/jordan-hoodies-002/front.webp';
import Img_10_Hover from '@/images/curated/sports/football/jordan/hoodies/jordan-hoodies-002/back.webp';
import Img_10_Gal_1 from '@/images/curated/sports/football/jordan/hoodies/jordan-hoodies-002/back.webp';
import Img_11_Main from '@/images/curated/sports/football/jordan/pants/jordan-pants-001/front.webp';
import Img_11_Hover from '@/images/curated/sports/football/jordan/pants/jordan-pants-001/back.webp';
import Img_11_Gal_1 from '@/images/curated/sports/football/jordan/pants/jordan-pants-001/back.webp';
import Img_12_Main from '@/images/curated/sports/football/jordan/pants/jordan-pants-002/front.webp';
import Img_12_Hover from '@/images/curated/sports/football/jordan/pants/jordan-pants-002/back.webp';
import Img_12_Gal_1 from '@/images/curated/sports/football/jordan/pants/jordan-pants-002/back.webp';
import Img_13_Main from '@/images/curated/sports/football/jordan/trucksuits/jordan-trucksuits-001/front.webp';
import Img_13_Hover from '@/images/curated/sports/football/jordan/trucksuits/jordan-trucksuits-001/back.webp';
import Img_13_Gal_1 from '@/images/curated/sports/football/jordan/trucksuits/jordan-trucksuits-001/back.webp';
import Img_14_Main from '@/images/curated/sports/football/jordan/trucksuits/jordan-trucksuits-002/front.webp';
import Img_14_Hover from '@/images/curated/sports/football/jordan/trucksuits/jordan-trucksuits-002/back.webp';
import Img_14_Gal_1 from '@/images/curated/sports/football/jordan/trucksuits/jordan-trucksuits-002/back.webp';
import Img_15_Main from '@/images/curated/sports/football/jordan/trucksuits/jordan-trucksuits-003/front.webp';
import Img_15_Hover from '@/images/curated/sports/football/jordan/trucksuits/jordan-trucksuits-003/back.webp';
import Img_15_Gal_1 from '@/images/curated/sports/football/jordan/trucksuits/jordan-trucksuits-003/back.webp';
import Img_16_Main from '@/images/curated/sports/gym/jordan/shorts/jordan-shorts-001/front.webp';
import Img_16_Hover from '@/images/curated/sports/gym/jordan/shorts/jordan-shorts-001/back.webp';
import Img_16_Gal_1 from '@/images/curated/sports/gym/jordan/shorts/jordan-shorts-001/back.webp';
import Img_17_Main from '@/images/curated/sports/gym/jordan/shorts/jordan-shorts-002/front.webp';
import Img_17_Hover from '@/images/curated/sports/gym/jordan/shorts/jordan-shorts-002/back.webp';
import Img_17_Gal_1 from '@/images/curated/sports/gym/jordan/shorts/jordan-shorts-002/back.webp';
import Img_18_Main from '@/images/curated/sports/gym/jordan/shorts/jordan-shorts-003/front.webp';
import Img_18_Hover from '@/images/curated/sports/gym/jordan/shorts/jordan-shorts-003/back.webp';
import Img_18_Gal_1 from '@/images/curated/sports/gym/jordan/shorts/jordan-shorts-003/back.webp';
import Img_19_Main from '@/images/curated/sports/gym/jordan/tanks/jordan-tanks-001/front.webp';
import Img_19_Hover from '@/images/curated/sports/gym/jordan/tanks/jordan-tanks-001/back.webp';
import Img_19_Gal_1 from '@/images/curated/sports/gym/jordan/tanks/jordan-tanks-001/back.webp';
import Img_20_Main from '@/images/curated/sports/gym/jordan/tanks/jordan-tanks-002/front.webp';
import Img_20_Hover from '@/images/curated/sports/gym/jordan/tanks/jordan-tanks-002/back.webp';
import Img_20_Gal_1 from '@/images/curated/sports/gym/jordan/tanks/jordan-tanks-002/back.webp';
import Img_21_Main from '@/images/curated/sports/gym/jordan/tshirts/jordan-tshirts-001/front.webp';
import Img_21_Hover from '@/images/curated/sports/gym/jordan/tshirts/jordan-tshirts-001/back.webp';
import Img_21_Gal_1 from '@/images/curated/sports/gym/jordan/tshirts/jordan-tshirts-001/back.webp';
import Img_22_Main from '@/images/curated/sports/gym/jordan/tshirts/jordan-tshirts-002/front.webp';
import Img_22_Hover from '@/images/curated/sports/gym/jordan/tshirts/jordan-tshirts-002/back.webp';
import Img_22_Gal_1 from '@/images/curated/sports/gym/jordan/tshirts/jordan-tshirts-002/back.webp';
import Img_23_Main from '@/images/products/amiparis/hoodies/amiparis-hoodie-001/front.webp';
const Img_23_Hover = Img_23_Main;
import Img_24_Main from '@/images/products/amiparis/hoodies/amiparis-hoodie-002/front.webp';
const Img_24_Hover = Img_24_Main;
import Img_25_Main from '@/images/products/amiparis/hoodies/amiparis-hoodie-003/front.webp';
import Img_25_Hover from '@/images/products/amiparis/hoodies/amiparis-hoodie-003/back.webp';
import Img_25_Gal_1 from '@/images/products/amiparis/hoodies/amiparis-hoodie-003/back.webp';
import Img_26_Main from '@/images/products/amiparis/hoodies/amiparis-hoodie-004/front.webp';
import Img_26_Hover from '@/images/products/amiparis/hoodies/amiparis-hoodie-004/back.webp';
import Img_26_Gal_1 from '@/images/products/amiparis/hoodies/amiparis-hoodie-004/back.webp';
import Img_27_Main from '@/images/products/amiparis/hoodies/amiparis-hoodie-005/front.webp';
const Img_27_Hover = Img_27_Main;
import Img_28_Main from '@/images/products/amiparis/hoodies/amiparis-hoodie-006/front.webp';
const Img_28_Hover = Img_28_Main;
import Img_29_Main from '@/images/products/amiparis/hoodies/amiparis-hoodie-007/front.webp';
const Img_29_Hover = Img_29_Main;
import Img_30_Main from '@/images/products/amiparis/hoodies/amiparis-hoodie-008/front.webp';
const Img_30_Hover = Img_30_Main;
import Img_31_Main from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-001/front.webp';
const Img_31_Hover = Img_31_Main;
import Img_32_Main from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-002/front.webp';
const Img_32_Hover = Img_32_Main;
import Img_33_Main from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-003/front.webp';
import Img_33_Hover from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-003/detail1.webp';
import Img_33_Gal_1 from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-003/detail1.webp';
import Img_33_Gal_2 from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-003/detail2.webp';
import Img_34_Main from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-004/front.webp';
import Img_34_Hover from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-004/detail1.webp';
import Img_34_Gal_1 from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-004/detail1.webp';
import Img_34_Gal_2 from '@/images/products/amiparis/iphone_case/amiparis-iphone_case-004/detail2.webp';
import Img_35_Main from '@/images/products/amiparis/polos/amiparis-polo-001/front.webp';
const Img_35_Hover = Img_35_Main;
import Img_36_Main from '@/images/products/amiparis/polos/amiparis-polo-002/front.webp';
const Img_36_Hover = Img_36_Main;
import Img_37_Main from '@/images/products/amiparis/polos/amiparis-polo-003/front.webp';
const Img_37_Hover = Img_37_Main;
import Img_38_Main from '@/images/products/amiparis/shorts/amiparis-shorts-001/front.webp';
const Img_38_Hover = Img_38_Main;
import Img_39_Main from '@/images/products/amiparis/shorts/amiparis-shorts-002/front.webp';
const Img_39_Hover = Img_39_Main;
import Img_40_Main from '@/images/products/amiparis/shorts/amiparis-shorts-003/front.webp';
const Img_40_Hover = Img_40_Main;
import Img_41_Main from '@/images/products/amiparis/shorts/amiparis-shorts-004/front.webp';
const Img_41_Hover = Img_41_Main;
import Img_42_Main from '@/images/products/amiparis/shorts/amiparis-shorts-005/front.webp';
const Img_42_Hover = Img_42_Main;
import Img_43_Main from '@/images/products/amiparis/shorts/amiparis-shorts-006/front.webp';
const Img_43_Hover = Img_43_Main;
import Img_44_Main from '@/images/products/amiparis/shorts/amiparis-shorts-007/front.webp';
const Img_44_Hover = Img_44_Main;
import Img_45_Main from '@/images/products/amiparis/sweaters/amiparis-sweater-001/front.webp';
const Img_45_Hover = Img_45_Main;
import Img_46_Main from '@/images/products/amiparis/sweaters/amiparis-sweater-002/front.webp';
const Img_46_Hover = Img_46_Main;
import Img_47_Main from '@/images/products/amiparis/sweaters/amiparis-sweater-003/front.webp';
const Img_47_Hover = Img_47_Main;
import Img_48_Main from '@/images/products/amiparis/sweaters/amiparis-sweater-004/front.webp';
const Img_48_Hover = Img_48_Main;
import Img_49_Main from '@/images/products/amiparis/sweaters/amiparis-sweater-005/front.webp';
const Img_49_Hover = Img_49_Main;
import Img_50_Main from '@/images/products/amiparis/sweaters/amiparis-sweater-006/front.webp';
const Img_50_Hover = Img_50_Main;

export const products: Product[] = [
    {
        id: 'amiparis-best-sellers-amiparis-hoodie-001-1', 
        title: "Amiparis-hoodie-",
        price: 85,
        
        image: Img_1_Main,
        hoverImage: Img_1_Hover,
        gallery: [Img_1_Main],
        category: "Best Sellers",
        brand: "Amiparis",
        slug: "amiparis-best-sellers-amiparis-hoodie-001-1", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Best Sellers","football"]
    },
    {
        id: 'amiparis-best-sellers-amiparis-hoodie-002-2', 
        title: "Amiparis-hoodie-",
        price: 72,
        
        image: Img_2_Main,
        hoverImage: Img_2_Hover,
        gallery: [Img_2_Main],
        category: "Best Sellers",
        brand: "Amiparis",
        slug: "amiparis-best-sellers-amiparis-hoodie-002-2", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Best Sellers","football"]
    },
    {
        id: 'amiparis-best-sellers-amiparis-hoodie-003-3', 
        title: "Amiparis-hoodie-",
        price: 127,
        compareAtPrice: 162,
        image: Img_3_Main,
        hoverImage: Img_3_Hover,
        gallery: [Img_3_Main, Img_3_Gal_1],
        category: "Best Sellers",
        brand: "Amiparis",
        slug: "amiparis-best-sellers-amiparis-hoodie-003-3", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Best Sellers","football","sale"]
    },
    {
        id: 'amiparis-best-sellers-amiparis-hoodie-004-4', 
        title: "Amiparis-hoodie-",
        price: 239,
        
        image: Img_4_Main,
        hoverImage: Img_4_Hover,
        gallery: [Img_4_Main, Img_4_Gal_1],
        category: "Best Sellers",
        brand: "Amiparis",
        slug: "amiparis-best-sellers-amiparis-hoodie-004-4", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Best Sellers","football"]
    },
    {
        id: 'amiparis-best-sellers-amiparis-hoodie-005-5', 
        title: "Amiparis-hoodie-",
        price: 74,
        
        image: Img_5_Main,
        hoverImage: Img_5_Hover,
        gallery: [Img_5_Main],
        category: "Best Sellers",
        brand: "Amiparis",
        slug: "amiparis-best-sellers-amiparis-hoodie-005-5", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Best Sellers","football","gym"]
    },
    {
        id: 'amiparis-best-sellers-amiparis-hoodie-006-6', 
        title: "Amiparis-hoodie-",
        price: 75,
        
        image: Img_6_Main,
        hoverImage: Img_6_Hover,
        gallery: [Img_6_Main],
        category: "Best Sellers",
        brand: "Amiparis",
        slug: "amiparis-best-sellers-amiparis-hoodie-006-6", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Best Sellers","football"]
    },
    {
        id: 'amiparis-best-sellers-amiparis-hoodie-007-7', 
        title: "Amiparis-hoodie-",
        price: 186,
        
        image: Img_7_Main,
        hoverImage: Img_7_Hover,
        gallery: [Img_7_Main],
        category: "Best Sellers",
        brand: "Amiparis",
        slug: "amiparis-best-sellers-amiparis-hoodie-007-7", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Best Sellers","basketball","football"]
    },
    {
        id: 'amiparis-best-sellers-amiparis-hoodie-008-8', 
        title: "Amiparis-hoodie-",
        price: 179,
        compareAtPrice: 224,
        image: Img_8_Main,
        hoverImage: Img_8_Hover,
        gallery: [Img_8_Main],
        category: "Best Sellers",
        brand: "Amiparis",
        slug: "amiparis-best-sellers-amiparis-hoodie-008-8", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Best Sellers","gym","running","sale"]
    },
    {
        id: 'jordan-hoodies-jordan-hoodies-001-9', 
        title: "Jordan-hoodies-",
        price: 62,
        
        image: Img_9_Main,
        hoverImage: Img_9_Hover,
        gallery: [Img_9_Main, Img_9_Gal_1],
        category: "Hoodies",
        brand: "Jordan",
        slug: "jordan-hoodies-jordan-hoodies-001-9", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Hoodies","football"]
    },
    {
        id: 'jordan-hoodies-jordan-hoodies-002-10', 
        title: "Jordan-hoodies-",
        price: 196,
        
        image: Img_10_Main,
        hoverImage: Img_10_Hover,
        gallery: [Img_10_Main, Img_10_Gal_1],
        category: "Hoodies",
        brand: "Jordan",
        slug: "jordan-hoodies-jordan-hoodies-002-10", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Hoodies","football"]
    },
    {
        id: 'jordan-pants-jordan-pants-001-11', 
        title: "Jordan-pants-",
        price: 226,
        
        image: Img_11_Main,
        hoverImage: Img_11_Hover,
        gallery: [Img_11_Main, Img_11_Gal_1],
        category: "Pants",
        brand: "Jordan",
        slug: "jordan-pants-jordan-pants-001-11", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Pants","football"]
    },
    {
        id: 'jordan-pants-jordan-pants-002-12', 
        title: "Jordan-pants-",
        price: 105,
        
        image: Img_12_Main,
        hoverImage: Img_12_Hover,
        gallery: [Img_12_Main, Img_12_Gal_1],
        category: "Pants",
        brand: "Jordan",
        slug: "jordan-pants-jordan-pants-002-12", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Pants","football"]
    },
    {
        id: 'jordan-trucksuits-jordan-trucksuits-001-13', 
        title: "Jordan-trucksuits-",
        price: 114,
        compareAtPrice: 146,
        image: Img_13_Main,
        hoverImage: Img_13_Hover,
        gallery: [Img_13_Main, Img_13_Gal_1],
        category: "Trucksuits",
        brand: "Jordan",
        slug: "jordan-trucksuits-jordan-trucksuits-001-13", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Trucksuits","football","sale"]
    },
    {
        id: 'jordan-trucksuits-jordan-trucksuits-002-14', 
        title: "Jordan-trucksuits-",
        price: 53,
        
        image: Img_14_Main,
        hoverImage: Img_14_Hover,
        gallery: [Img_14_Main, Img_14_Gal_1],
        category: "Trucksuits",
        brand: "Jordan",
        slug: "jordan-trucksuits-jordan-trucksuits-002-14", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Trucksuits","football"]
    },
    {
        id: 'jordan-trucksuits-jordan-trucksuits-003-15', 
        title: "Jordan-trucksuits-",
        price: 243,
        
        image: Img_15_Main,
        hoverImage: Img_15_Hover,
        gallery: [Img_15_Main, Img_15_Gal_1],
        category: "Trucksuits",
        brand: "Jordan",
        slug: "jordan-trucksuits-jordan-trucksuits-003-15", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Trucksuits","football"]
    },
    {
        id: 'jordan-shorts-jordan-shorts-001-16', 
        title: "Jordan-shorts-",
        price: 52,
        compareAtPrice: 72,
        image: Img_16_Main,
        hoverImage: Img_16_Hover,
        gallery: [Img_16_Main, Img_16_Gal_1],
        category: "Shorts",
        brand: "Jordan",
        slug: "jordan-shorts-jordan-shorts-001-16", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Shorts","gym","sale"]
    },
    {
        id: 'jordan-shorts-jordan-shorts-002-17', 
        title: "Jordan-shorts-",
        price: 160,
        compareAtPrice: 202,
        image: Img_17_Main,
        hoverImage: Img_17_Hover,
        gallery: [Img_17_Main, Img_17_Gal_1],
        category: "Shorts",
        brand: "Jordan",
        slug: "jordan-shorts-jordan-shorts-002-17", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Shorts","gym","sale"]
    },
    {
        id: 'jordan-shorts-jordan-shorts-003-18', 
        title: "Jordan-shorts-",
        price: 186,
        
        image: Img_18_Main,
        hoverImage: Img_18_Hover,
        gallery: [Img_18_Main, Img_18_Gal_1],
        category: "Shorts",
        brand: "Jordan",
        slug: "jordan-shorts-jordan-shorts-003-18", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Shorts","gym"]
    },
    {
        id: 'jordan-tanks-jordan-tanks-001-19', 
        title: "Jordan-tanks-",
        price: 171,
        
        image: Img_19_Main,
        hoverImage: Img_19_Hover,
        gallery: [Img_19_Main, Img_19_Gal_1],
        category: "Tanks",
        brand: "Jordan",
        slug: "jordan-tanks-jordan-tanks-001-19", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Tanks","gym"]
    },
    {
        id: 'jordan-tanks-jordan-tanks-002-20', 
        title: "Jordan-tanks-",
        price: 155,
        compareAtPrice: 196,
        image: Img_20_Main,
        hoverImage: Img_20_Hover,
        gallery: [Img_20_Main, Img_20_Gal_1],
        category: "Tanks",
        brand: "Jordan",
        slug: "jordan-tanks-jordan-tanks-002-20", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","Tanks","gym","sale"]
    },
    {
        id: 'jordan-tshirts-jordan-tshirts-001-21', 
        title: "Jordan-tshirts-",
        price: 166,
        
        image: Img_21_Main,
        hoverImage: Img_21_Hover,
        gallery: [Img_21_Main, Img_21_Gal_1],
        category: "T-Shirts",
        brand: "Jordan",
        slug: "jordan-tshirts-jordan-tshirts-001-21", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","T-Shirts","gym"]
    },
    {
        id: 'jordan-tshirts-jordan-tshirts-002-22', 
        title: "Jordan-tshirts-",
        price: 153,
        
        image: Img_22_Main,
        hoverImage: Img_22_Hover,
        gallery: [Img_22_Main, Img_22_Gal_1],
        category: "T-Shirts",
        brand: "Jordan",
        slug: "jordan-tshirts-jordan-tshirts-002-22", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Jordan","T-Shirts","gym"]
    },
    {
        id: 'amiparis-hoodies-amiparis-hoodie-001-23', 
        title: "Amiparis-hoodie-",
        price: 145,
        
        image: Img_23_Main,
        hoverImage: Img_23_Hover,
        gallery: [Img_23_Main],
        category: "Hoodies",
        brand: "Amiparis",
        slug: "amiparis-hoodies-amiparis-hoodie-001-23", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Hoodies","football"]
    },
    {
        id: 'amiparis-hoodies-amiparis-hoodie-002-24', 
        title: "Amiparis-hoodie-",
        price: 141,
        
        image: Img_24_Main,
        hoverImage: Img_24_Hover,
        gallery: [Img_24_Main],
        category: "Hoodies",
        brand: "Amiparis",
        slug: "amiparis-hoodies-amiparis-hoodie-002-24", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Hoodies","football","basketball"]
    },
    {
        id: 'amiparis-hoodies-amiparis-hoodie-003-25', 
        title: "Amiparis-hoodie-",
        price: 172,
        
        image: Img_25_Main,
        hoverImage: Img_25_Hover,
        gallery: [Img_25_Main, Img_25_Gal_1],
        category: "Hoodies",
        brand: "Amiparis",
        slug: "amiparis-hoodies-amiparis-hoodie-003-25", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Hoodies","gym"]
    },
    {
        id: 'amiparis-hoodies-amiparis-hoodie-004-26', 
        title: "Amiparis-hoodie-",
        price: 150,
        
        image: Img_26_Main,
        hoverImage: Img_26_Hover,
        gallery: [Img_26_Main, Img_26_Gal_1],
        category: "Hoodies",
        brand: "Amiparis",
        slug: "amiparis-hoodies-amiparis-hoodie-004-26", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Hoodies","football","basketball"]
    },
    {
        id: 'amiparis-hoodies-amiparis-hoodie-005-27', 
        title: "Amiparis-hoodie-",
        price: 240,
        
        image: Img_27_Main,
        hoverImage: Img_27_Hover,
        gallery: [Img_27_Main],
        category: "Hoodies",
        brand: "Amiparis",
        slug: "amiparis-hoodies-amiparis-hoodie-005-27", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Hoodies","gym","running"]
    },
    {
        id: 'amiparis-hoodies-amiparis-hoodie-006-28', 
        title: "Amiparis-hoodie-",
        price: 216,
        
        image: Img_28_Main,
        hoverImage: Img_28_Hover,
        gallery: [Img_28_Main],
        category: "Hoodies",
        brand: "Amiparis",
        slug: "amiparis-hoodies-amiparis-hoodie-006-28", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Hoodies","football"]
    },
    {
        id: 'amiparis-hoodies-amiparis-hoodie-007-29', 
        title: "Amiparis-hoodie-",
        price: 127,
        
        image: Img_29_Main,
        hoverImage: Img_29_Hover,
        gallery: [Img_29_Main],
        category: "Hoodies",
        brand: "Amiparis",
        slug: "amiparis-hoodies-amiparis-hoodie-007-29", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Hoodies","running"]
    },
    {
        id: 'amiparis-hoodies-amiparis-hoodie-008-30', 
        title: "Amiparis-hoodie-",
        price: 230,
        compareAtPrice: 286,
        image: Img_30_Main,
        hoverImage: Img_30_Hover,
        gallery: [Img_30_Main],
        category: "Hoodies",
        brand: "Amiparis",
        slug: "amiparis-hoodies-amiparis-hoodie-008-30", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Hoodies","running","sale"]
    },
    {
        id: 'amiparis-iphone-case-amiparis-iphone-case-001-31', 
        title: "Amiparis-iphone case-",
        price: 141,
        
        image: Img_31_Main,
        hoverImage: Img_31_Hover,
        gallery: [Img_31_Main],
        category: "Iphone case",
        brand: "Amiparis",
        slug: "amiparis-iphone-case-amiparis-iphone-case-001-31", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Iphone case","basketball"]
    },
    {
        id: 'amiparis-iphone-case-amiparis-iphone-case-002-32', 
        title: "Amiparis-iphone case-",
        price: 126,
        compareAtPrice: 161,
        image: Img_32_Main,
        hoverImage: Img_32_Hover,
        gallery: [Img_32_Main],
        category: "Iphone case",
        brand: "Amiparis",
        slug: "amiparis-iphone-case-amiparis-iphone-case-002-32", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Iphone case","gym","sale"]
    },
    {
        id: 'amiparis-iphone-case-amiparis-iphone-case-003-33', 
        title: "Amiparis-iphone case-",
        price: 58,
        
        image: Img_33_Main,
        hoverImage: Img_33_Hover,
        gallery: [Img_33_Main, Img_33_Gal_1, Img_33_Gal_2],
        category: "Iphone case",
        brand: "Amiparis",
        slug: "amiparis-iphone-case-amiparis-iphone-case-003-33", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Iphone case","running"]
    },
    {
        id: 'amiparis-iphone-case-amiparis-iphone-case-004-34', 
        title: "Amiparis-iphone case-",
        price: 51,
        
        image: Img_34_Main,
        hoverImage: Img_34_Hover,
        gallery: [Img_34_Main, Img_34_Gal_1, Img_34_Gal_2],
        category: "Iphone case",
        brand: "Amiparis",
        slug: "amiparis-iphone-case-amiparis-iphone-case-004-34", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Iphone case","gym"]
    },
    {
        id: 'amiparis-polos-amiparis-polo-001-35', 
        title: "Amiparis-polo-",
        price: 141,
        
        image: Img_35_Main,
        hoverImage: Img_35_Hover,
        gallery: [Img_35_Main],
        category: "Polos",
        brand: "Amiparis",
        slug: "amiparis-polos-amiparis-polo-001-35", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Polos","football","basketball"]
    },
    {
        id: 'amiparis-polos-amiparis-polo-002-36', 
        title: "Amiparis-polo-",
        price: 131,
        compareAtPrice: 167,
        image: Img_36_Main,
        hoverImage: Img_36_Hover,
        gallery: [Img_36_Main],
        category: "Polos",
        brand: "Amiparis",
        slug: "amiparis-polos-amiparis-polo-002-36", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Polos","running","sale"]
    },
    {
        id: 'amiparis-polos-amiparis-polo-003-37', 
        title: "Amiparis-polo-",
        price: 54,
        
        image: Img_37_Main,
        hoverImage: Img_37_Hover,
        gallery: [Img_37_Main],
        category: "Polos",
        brand: "Amiparis",
        slug: "amiparis-polos-amiparis-polo-003-37", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Polos","football"]
    },
    {
        id: 'amiparis-shorts-amiparis-shorts-001-38', 
        title: "Amiparis-shorts-",
        price: 165,
        
        image: Img_38_Main,
        hoverImage: Img_38_Hover,
        gallery: [Img_38_Main],
        category: "Shorts",
        brand: "Amiparis",
        slug: "amiparis-shorts-amiparis-shorts-001-38", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Shorts","gym","running"]
    },
    {
        id: 'amiparis-shorts-amiparis-shorts-002-39', 
        title: "Amiparis-shorts-",
        price: 231,
        
        image: Img_39_Main,
        hoverImage: Img_39_Hover,
        gallery: [Img_39_Main],
        category: "Shorts",
        brand: "Amiparis",
        slug: "amiparis-shorts-amiparis-shorts-002-39", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Shorts","football","gym"]
    },
    {
        id: 'amiparis-shorts-amiparis-shorts-003-40', 
        title: "Amiparis-shorts-",
        price: 145,
        
        image: Img_40_Main,
        hoverImage: Img_40_Hover,
        gallery: [Img_40_Main],
        category: "Shorts",
        brand: "Amiparis",
        slug: "amiparis-shorts-amiparis-shorts-003-40", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Shorts","basketball"]
    },
    {
        id: 'amiparis-shorts-amiparis-shorts-004-41', 
        title: "Amiparis-shorts-",
        price: 179,
        
        image: Img_41_Main,
        hoverImage: Img_41_Hover,
        gallery: [Img_41_Main],
        category: "Shorts",
        brand: "Amiparis",
        slug: "amiparis-shorts-amiparis-shorts-004-41", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Shorts","gym"]
    },
    {
        id: 'amiparis-shorts-amiparis-shorts-005-42', 
        title: "Amiparis-shorts-",
        price: 94,
        
        image: Img_42_Main,
        hoverImage: Img_42_Hover,
        gallery: [Img_42_Main],
        category: "Shorts",
        brand: "Amiparis",
        slug: "amiparis-shorts-amiparis-shorts-005-42", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Shorts","gym","basketball"]
    },
    {
        id: 'amiparis-shorts-amiparis-shorts-006-43', 
        title: "Amiparis-shorts-",
        price: 233,
        
        image: Img_43_Main,
        hoverImage: Img_43_Hover,
        gallery: [Img_43_Main],
        category: "Shorts",
        brand: "Amiparis",
        slug: "amiparis-shorts-amiparis-shorts-006-43", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Shorts","gym","football"]
    },
    {
        id: 'amiparis-shorts-amiparis-shorts-007-44', 
        title: "Amiparis-shorts-",
        price: 87,
        
        image: Img_44_Main,
        hoverImage: Img_44_Hover,
        gallery: [Img_44_Main],
        category: "Shorts",
        brand: "Amiparis",
        slug: "amiparis-shorts-amiparis-shorts-007-44", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Shorts","football"]
    },
    {
        id: 'amiparis-sweaters-amiparis-sweater-001-45', 
        title: "Amiparis-sweater-",
        price: 58,
        compareAtPrice: 79,
        image: Img_45_Main,
        hoverImage: Img_45_Hover,
        gallery: [Img_45_Main],
        category: "Sweaters",
        brand: "Amiparis",
        slug: "amiparis-sweaters-amiparis-sweater-001-45", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Sweaters","football","sale"]
    },
    {
        id: 'amiparis-sweaters-amiparis-sweater-002-46', 
        title: "Amiparis-sweater-",
        price: 177,
        compareAtPrice: 222,
        image: Img_46_Main,
        hoverImage: Img_46_Hover,
        gallery: [Img_46_Main],
        category: "Sweaters",
        brand: "Amiparis",
        slug: "amiparis-sweaters-amiparis-sweater-002-46", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Sweaters","gym","running","sale"]
    },
    {
        id: 'amiparis-sweaters-amiparis-sweater-003-47', 
        title: "Amiparis-sweater-",
        price: 167,
        
        image: Img_47_Main,
        hoverImage: Img_47_Hover,
        gallery: [Img_47_Main],
        category: "Sweaters",
        brand: "Amiparis",
        slug: "amiparis-sweaters-amiparis-sweater-003-47", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Sweaters","football"]
    },
    {
        id: 'amiparis-sweaters-amiparis-sweater-004-48', 
        title: "Amiparis-sweater-",
        price: 59,
        compareAtPrice: 80,
        image: Img_48_Main,
        hoverImage: Img_48_Hover,
        gallery: [Img_48_Main],
        category: "Sweaters",
        brand: "Amiparis",
        slug: "amiparis-sweaters-amiparis-sweater-004-48", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Sweaters","football","basketball","sale"]
    },
    {
        id: 'amiparis-sweaters-amiparis-sweater-005-49', 
        title: "Amiparis-sweater-",
        price: 65,
        
        image: Img_49_Main,
        hoverImage: Img_49_Hover,
        gallery: [Img_49_Main],
        category: "Sweaters",
        brand: "Amiparis",
        slug: "amiparis-sweaters-amiparis-sweater-005-49", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Sweaters","football","basketball"]
    },
    {
        id: 'amiparis-sweaters-amiparis-sweater-006-50', 
        title: "Amiparis-sweater-",
        price: 61,
        
        image: Img_50_Main,
        hoverImage: Img_50_Hover,
        gallery: [Img_50_Main],
        category: "Sweaters",
        brand: "Amiparis",
        slug: "amiparis-sweaters-amiparis-sweater-006-50", // Use uniqueId as slug too
        gender: "unisex", 
        tags: ["Amiparis","Sweaters","running","basketball"]
    }
];
